In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#numpy do not store data, so changes futher down will effec the main body

In [5]:
#but to copy and not affect the data
arr_copy = arr.copy()

In [6]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) #see the square brackets at thwe start to differentiate

In [12]:
array_2d[0,0] #first row index is 0 similarly first column index is also 0

1

In [14]:
array_2d[1][1] #element wise

5

In [15]:
arr = np.arange(1,11)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

CONDITIONAL SELECTION

In [19]:
#boolean operators
bool_arr = arr > 5

In [21]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [22]:
#OR ***
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [23]:
b = np.arange(50).reshape(5,10)

In [24]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [25]:
b[2,4]

24

In [26]:
b[2:4,2:5]

array([[22, 23, 24],
       [32, 33, 34]])