In [1]:
my_list =[1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [8]:
my_maths = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_maths

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_maths)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5)) #tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,5,10) # number of points between certain numbers, (including the numbers)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(3,4) #no tuples here

array([[0.11882917, 0.69413214, 0.19588421, 0.68107807],
       [0.89476416, 0.43978206, 0.67381191, 0.81925227],
       [0.97953652, 0.3574825 , 0.14848925, 0.12339868]])

In [28]:
 np.random.randn(2) #no tuples here also

array([-0.12413456,  0.92199696])

In [29]:
np.random.randint(1,100)

21

In [31]:
np.random.randint(1,100,10) #linspace distributes equally while this distributes randomly

array([ 3, 18, 40, 34, 67, 82, 43, 59, 25, 41])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranrr = np.random.randint(0,50,10)

In [35]:
ranrr

array([39,  6,  7, 43,  8, 17, 26,  7, 36, 39])

In [37]:
arr.reshape(5,5) #if you cant fill the matrix you will get error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranrr

array([39,  6,  7, 43,  8, 17, 26,  7, 36, 39])

In [40]:
ranrr.max()

43

In [41]:
ranrr.min()

6

In [42]:
ranrr.argmax()

3

In [43]:
ranrr.argmin()

1

In [47]:
ranrr.shape #no brackets

(10,)

In [49]:
arr.dtype

dtype('int32')

In [50]:
from numpy.random import randint

In [55]:
s = {randint(2,5,6)}

TypeError: unhashable type: 'numpy.ndarray'

In [54]:
s

[array([3, 3, 4, 3, 2, 4])]

In [56]:
s = {1,2,2,3,3,4,5,6}

In [57]:
s

{1, 2, 3, 4, 5, 6}